name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-24.04
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Cache Bundler dependencies
      - name: Cache Gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Step 3: Set up Ruby with a compatible version
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # Ensure Ruby 3.1 is used for compatibility
          bundler-cache: true # Cache Bundler dependencies automatically

      # Step 4: JSON Syntax Check
      - name: Check JSON Syntax
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\bio.json$"

      # Step 5: Build and Deploy Jekyll Site
      - name: Build and Deploy Jekyll Site
        uses: helaili/jekyll-action@2.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'gh-pages'
